<?php

namespace SB\FormulaireBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DVDRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DVDRepository extends EntityRepository
{
}
